### ISSUE TITLE
hostname was not match with the server certificate

### ISSUE THREAD

**Issue by dongennl** [dkd/paymill-ruby#6] opened 2012-11-26 22:10 UTC
Hi,

trying this out and thanks for creating this gem

I'm using the code from another question on here:

result = Paymill::Transaction.create(amount: 2000,
                               currency:    "EUR",
                               description: "Milestone payment",
                              token:       token)

but this gives me an error:
'hostname was not match with the server certificate'

seems to be some sort of SSL error. I'm totally stuck. 
Many thanks for any help.

**Comment by flippingbits** [comment] 2012-11-26 22:16
Are you using a proxy?

**Comment by flippingbits** [comment] 2012-11-27 14:08
I'm closing this issue since this might be caused by your local setup.

**Closed as completed by flippingbits** 2012-11-27 14:08 UTC

**Comment by dongennl** [comment] 2012-11-27 20:11
hi, no proxy; 
it works fine if I change:
https.verify_mode = OpenSSL::SSL::VERIFY_PEER to VERIFY_NONE but obviously that's not ok for production.

Are you sure the certificate is ok?

**Comment by flippingbits** [comment] 2012-11-27 20:55
yes, you might compare https://github.com/dkd/paymill-ruby/blob/master/lib/data/paymill.crt with https://github.com/Paymill/Paymill-PHP/blob/master/lib/Services/Paymill/Apiclient/paymill.crt

**Comment by abarre** [comment] 2012-12-12 17:06
I have the same problem with the certificate.
@dongennl, did you resolve your problem?

**Comment by abarre** [comment] 2012-12-15 09:40
Actually, I solved the problem on my mac by updating openssl, ruby and rails to the last version.
I don't know which part wasn't fine.

**Comment by flippingbits** [comment] 2012-12-15 09:53
Hm, since we don't depend on rails it will leave ruby and openssl.
Which ruby version have you used before?

I've tested the code only with Ruby 1.9.3. But I'm eager to make it compatible with Ruby 1.8 if it's not.

**Comment by abarre** [comment] 2012-12-17 09:41
Today, I did some more test :
- openssl 0.9.8r (default on my mac) + ruby 1.8.7 => KO
- openssl 1.0.1c + ruby 1.8.7 => KO
- openssl 1.0.1c + ruby 1.9.3-p327 => OK
- openssl 0.9.8r + ruby 1.9.3-p327 => OK

To test, I do that : 

```
brew install openssl
CONFIGURE_OPTS="--with-openssl-dir=`brew --prefix openssl`" rbenv install 1.8.7-p371 

or 

CONFIGURE_OPTS="--with-openssl-dir=`brew --prefix openssl`" rbenv install 1.9.3-p327
```

So, the responsible seems to be ruby.

**Comment by flippingbits** [comment] 2012-12-17 10:29
Thank you for testing this issue. I'll write a note in the readme that this gem supports only 1.9.

**Comment by abarre** [comment] 2012-12-17 19:09
I dig into the issue in the openssl file in ruby and it seems that paymill doen't send the same certificate for ruby 1.8.7 and 1.9.3. I don't know if the requests are different.

For 1.8.7

```
[authorityKeyIdentifier = keyid:99:E4:40:5F:6B:14:5E:3E:05:D9:DD:D3:63:54:FC:62:B8:F7:00:AC, ,
 subjectKeyIdentifier = 8C:79:9D:60:79:F8:E6:23:56:DF:99:66:3D:48:36:6D:C4:02:05:05,
 keyUsage = critical, Digital Signature, Key Encipherment,
 basicConstraints = critical, CA:FALSE,
 extendedKeyUsage = TLS Web Server Authentication, TLS Web Client Authentication,
 certificatePolicies = Policy: 1.3.6.1.4.1.6449.1.2.2.7,   CPS: http://www.positivessl.com/CPS, ,
 crlDistributionPoints = , Full Name:,   URI:http://crl.comodoca.com/PositiveSSLCA2.crl, ,
 authorityInfoAccess = CA Issuers - URI:http://crt.comodoca.com/PositiveSSLCA2.crt, OCSP - URI:http://ocsp.comodoca.com, ,
 subjectAltName = DNS:*.paymill.com, DNS:paymill.com]
```

For 1.9.3

```
[authorityKeyIdentifier = keyid:99:E4:40:5F:6B:14:5E:3E:05:D9:DD:D3:63:54:FC:62:B8:F7:00:AC, ,
 subjectKeyIdentifier = A0:C0:59:C9:F0:12:63:F6:D5:E0:AE:C9:90:4C:4C:74:67:C3:12:AF,
 keyUsage = critical, Digital Signature, Key Encipherment,
 basicConstraints = critical, CA:FALSE,
 extendedKeyUsage = TLS Web Server Authentication, TLS Web Client Authentication,
 certificatePolicies = Policy: 1.3.6.1.4.1.6449.1.2.2.7,   CPS: http://www.positivessl.com/CPS, ,
 crlDistributionPoints = , Full Name:,   URI:http://crl.comodoca.com/PositiveSSLCA2.crl, ,
 authorityInfoAccess = CA Issuers - URI:http://crt.comodoca.com/PositiveSSLCA2.crt, OCSP - URI:http://ocsp.comodoca.com, ,
 subjectAltName = DNS:*.paymill.de, DNS:paymill.de]
```

Look at the last line, you can notice the _paymill.com_ in the certificate from the server when the request is done in ruby 1.8.7.

I will send a mail to the paymill support.

**Comment by ebellity** [comment] 2012-12-21 15:03
I had the same problem. Had to update the ruby version on my terminal from 1.8.7 to 1.9.2 and now it works.

**Comment by dongennl** [comment] 2013-02-28 13:14
Hi, some of the errors seem related to OS X and OpenSSL; if you get that (my original error on #6 ) this fixed it for me:
rvm pkg install openssl
rvm remove 1.9.3
rvm install 1.9.3 --with-openssl-dir=$rvm_path/usr --with-gcc=clang
